title: 邵铭塬 (Mingyuan Shao)'s Homepage
page-top-title: 邵铭塬 (Mingyuan Shao)
top-section-bg-text: 厦门大学 电子科学与技术学院
home-subtitle: 邵铭塬&ensp;|&ensp;Mingyuan Shao
copyright-text: '&copy; 邵铭塬 (Mingyuan Shao) 2024-2025. All Rights Reserved.'
